# models/__init__.py

from .client_model import Client
from .geography_model import Geography

from .ISAFACT.client_ISAFACT_model import Client_ISAFACT
from .DIVALTO.CLI_DIVALTO_model import Client_DIVALTO
from .ISAFACT.CLI_model_ISFACT import CLI_ISFACT
from .ISAFACT.STATION_model_ISFACT import SITE_ISAFACT
from .ISAFACT.RIB_model import RIB_ISAFACT
from .ISAFACT.SITE_GEOCODAGE_model import SITE_GEOCODAGE

from .EQUIV_DIVALO_ISA.EQUIV_ISA_DIVALTO_REGLEMENT_model import EQUIV_MODE_RGLT_ISA_DIV
from .EQUIV_DIVALO_ISA.T119_CATEGORIE_CLIENT_model import T119_CATEG_CLIENT
from .EQUIV_DIVALO_ISA.ARTICLE_FACTURATION_CONTRAT_model import ARTICLE_FACTURATION_CONTRAT
from .EQUIV_DIVALO_ISA.CONTRAT_MODELE_model import CONTRAT_MODEL
from .EQUIV_DIVALO_ISA.TYPE_MATERIEL_model import TYPE_MATERIEL