# services/__init__.py

from .Extract_info_from_pdf import extract_text_from_pdf, search_patterns, create_excel_file
from .Extract_info_excel import exporter_cli_isfact_excel
from .DB_service import Lire_BD_DIVALTO, Ecrire_MAJ_Clients_DIVALTO, lire_donnees_ISAFACT, Ecrire_MAJ_Clients_ISFACT, testServiceDB, lire_ecrire_mettre_a_jour_fichier_csv, lire_base_de_donnes_client, lire_ercrire_mettre_a_jour_table_geography, lire_donnees_BD_geography
from .DB_operations_service import  MaJ_Table_CLI_BY_ISAFACT, lire_donnees_CLI_ISAFACT, lire_donnes_SITE_ISFACT, KillAllTable, lire_donnes_RIB_ISFACT
from .DB_SITES_service import Transfert_donnes_CLIENT_ISAFACT_SITES, numerotation_sites, correspondance_clientID_siteID
from .DB_CLI_services import Transfert_donnes_CLIENT_ISAFACT_CLI, suppression_doublon_by_TEL1, suppression_doublon_by_TEL2, suppression_doublon_by_EMAIL, suppression_doublon_by_TEL1_ET_TEL2, numerotation_client, CodeStatisitique_CLI
from .DB_RIB_service import Ecrire_Table_RIB_from_ISAFACT
from .DB_GEOCODING_service import Ecrire_base_GEOCODAGE
from .DB_MODE_RGLT_service import initialisation_mode_paiement